### PR TITLE
Add historical detectors

### PR DESCRIPTION
**Pull request by ohltyler**
*Issue #, if available:*

*Description of changes:*

This PR adds the historical detectors to the plugin. The `historical-workbench-dev` branch includes the 5 approved PRs related to the changes. This PR is just merging all of those changes into master.

Details of all of the changes & new pages can be found in the individual PRs below:
Historical detector list page: #347 
Create/edit historical detector page: #349 
Historical detector details/results page: #351 
Other changes to make historical detectors compatible: #352 
Bug fixes: #357 

Have confirmed all UT and IT pass.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by yizheliu-amazon — APPROVED** [review]

**Review by ylwu-amzn — APPROVED** [review]
LGTM. Thanks for the change!

**Comment by vijay-alphonso** [comment]
The historical detector does not allow categories

**Comment by agarwalvijay** [comment]
The historical detector does not seem to support "category" definition.

**Comment by ylwu-amzn** [comment]
hi, @agarwalvijay , thanks for your interest in historical detector. For this release in ODFE 1.13, we don't support high cardinality detector with "category" field. We are building unified flow now which will support "category" field and unify both realtime and historical detection under the same detector. You can check the RFC https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/380, welcome any suggestions/comments.

**Pull request merged**
