### PR TITLE
Adding release notes for 1.10.1.0

### PR DESCRIPTION
**Pull request by saratvemulapalli**
Updating release notes for Plugin 1.10.1.0 release

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ohltyler** [comment]
I think we just want to rename the 1.10.0.0 release notes rather than creating a new 1.10.1.0 one?

**Review by yizheliu-amazon — COMMENTED** [review]
Could you add PR 287 and 305?

**Comment by yizheliu-amazon** [comment]
> I think we just want to rename the 1.10.0.0 release notes rather than creating a new 1.10.1.0 one?

+1

**Comment by saratvemulapalli** [comment]
> I think we just want to rename the 1.10.0.0 release notes rather than creating a new 1.10.1.0 one?

Not sure how the old file delete was missed in this commit. I just re-named it. 
Let me cancel the PR and just send out another clean PR. 
Thanks for taking a look though. 

@yizheliu-amazon sure will add PR 287 and 305 (I believe release notes draft automation will takecare of it).

**Pull request closed without merging**
